services:
  mongodb:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: echobot
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
      - 27018:27018
      - 27019:27019

  mongodb-webui:
    image: mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    ports:
      - 8081:8081

  echobot:
    build:
      context: .
    restart: unless-stopped
    environment:
      OUTPUT_TYPE: "mongodb"
      SLEEP_TIME: "5s"
      MESSAGE: "Docker compose test"
      MONGODB_URI: "mongodb://root:password@mongodb:27017"
      MONGODB_DATABASE: "echobot"
      MONGODB_COLLECTION: "log"

