apiVersion: apps/v1
kind: Deployment
metadata:
  name: echobot
  namespace: gitops-series
  labels:
    name: echobot
spec:
  replicas: 1
  selector:
    matchLabels:
      name: echobot
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: echobot
    spec:
      containers:
        - name: echobot
          image: ghcr.io/sngular/gitops-echobot:v0.1.2
          env:
            - name: CHARACTER
              value: "Sngular utiliza GitOps con Flux en sus despliegues. Tag v0.1.2 desplegado!"
            - name: SLEEP
              value: "3s"
          resources:
            requests:
              cpu: 10m
              memory: 30Mi
            limits:
              cpu: 10m
              memory: 30Mi


